/* AUTO-GENERATED from data/products/*.json by build.js — do not edit here; edit products in the CMS (/admin). */
window.CATALOG = [
  {
    "id": "squishy-unicorn",
    "name": "Squishy Unicorn",
    "category": "Plushies",
    "subcategory": "Characters",
    "price": 150,
    "sale": 105,
    "image": "assets/products/squishy-unicorn.jpeg",
    "desc": "A huggable, made-to-order unicorn in plush chenille — candy-pink hooves, a buttercup horn and a face only a maker could give.",
    "featured": true,
    "isNew": false,
    "image2": "assets/products/squishy-unicorn-2.jpeg"
  },
  {
    "id": "sophie-basket",
    "name": "Sophie Basket",
    "category": "Bags",
    "subcategory": "",
    "price": 120,
    "sale": 84,
    "image": "assets/products/sophie-basket.jpg",
    "desc": "A hand-crocheted market basket in a painterly garden melange. Structured for the day, soft for the beach.",
    "featured": true,
    "isNew": false,
    "image2": "assets/products/sophie-basket-2.jpg"
  },
  {
    "id": "spring-hexagon-jacket-m-l",
    "name": "Spring Hexagon jacket (M/L)",
    "category": "Clothing",
    "subcategory": "",
    "price": 180,
    "sale": 126,
    "image": "assets/products/spring-hexagon-jacket-m-l.jpg",
    "desc": "A hooded granny-square jacket built from spring-bright hexagons. Heirloom energy, made to order.",
    "featured": true,
    "isNew": false,
    "image2": "assets/products/spring-hexagon-jacket-m-l-2.jpg"
  },
  {
    "id": "green-bolero-jacket-m-l",
    "name": "Green Cropped Jacket (M/L)",
    "category": "Clothing",
    "subcategory": "",
    "price": 150,
    "sale": 105,
    "image": "assets/products/green-bolero-jacket-m-l.jpg",
    "desc": "A cropped, open-front jacket in mossy greens — the throw-on layer for cool evenings.",
    "featured": true,
    "isNew": false,
    "image2": "assets/products/green-bolero-jacket-m-l-2.jpg"
  },
  {
    "id": "teal-velvet",
    "name": "Teal velvet",
    "category": "Accessories",
    "subcategory": "Scrunchies",
    "price": 20,
    "sale": 14,
    "image": "assets/products/teal-velvet.jpg",
    "desc": "A plush velvet-yarn scrunchie in deep teal. Gentle on hair, loud on charm.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/teal-velvet-2.jpg"
  },
  {
    "id": "brown-picot-bandana",
    "name": "Brown Picot Bandana",
    "category": "Accessories",
    "subcategory": "Bandanas",
    "price": 35,
    "sale": 24.5,
    "image": "assets/products/brown-picot-bandana.jpg",
    "desc": "A picot-edged hair bandana in cocoa brown. Ties at the nape, finishes any look.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/brown-picot-bandana-2.jpg"
  },
  {
    "id": "sweet-hello-cardigan",
    "name": "Daisy cardigan",
    "category": "Clothing",
    "subcategory": "",
    "price": 200,
    "sale": 140,
    "image": "assets/products/sweet-hello-cardigan.jpg",
    "desc": "The Daisy cardigan — a soft, daisy-flecked crochet that wears like a hug.",
    "featured": true,
    "isNew": false,
    "image2": "assets/products/sweet-hello-cardigan-2.jpg"
  },
  {
    "id": "picot-bandana-black",
    "name": "Picot bandana (Black)",
    "category": "Accessories",
    "subcategory": "Bandanas",
    "price": 35,
    "sale": 24.5,
    "image": "assets/products/picot-bandana-black.jpg",
    "desc": "The picot bandana in black — the most-worn thing you'll own.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/picot-bandana-black-2.jpg"
  },
  {
    "id": "blue-daze-cardigan-medium",
    "name": "Blue daze Cardigan",
    "category": "Clothing",
    "subcategory": "",
    "price": 300,
    "sale": null,
    "image": "assets/products/blue-daze-cardigan-medium.jpg",
    "desc": "Blue Daze: an open, airy cardigan in a hand-dyed blue melange, made to order.",
    "featured": false,
    "isNew": true,
    "image2": "assets/products/blue-daze-cardigan-medium-2.jpg"
  },
  {
    "id": "pink-picot-bandana",
    "name": "Pink Picot Bandana",
    "category": "Accessories",
    "subcategory": "Bandanas",
    "price": 35,
    "sale": 24.5,
    "image": "assets/products/pink-picot-bandana.jpg",
    "desc": "A sweet picot bandana in candy pink, scalloped by hand.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/pink-picot-bandana-2.jpg"
  },
  {
    "id": "dana-tote-bag-multicolour",
    "name": "Dana tote bag (Multicolour)",
    "category": "Bags",
    "subcategory": "",
    "price": 80,
    "sale": 48,
    "image": "assets/products/dana-tote-bag-multicolour.jpg",
    "desc": "The Dana tote in a full-spectrum multicolour — roomy, slouchy and impossible to buy twice the same.",
    "featured": true,
    "isNew": false,
    "image2": "assets/products/dana-tote-bag-multicolour-2.jpg"
  },
  {
    "id": "tao-tote-tropical-night",
    "name": "Tao tote (tropical night)",
    "category": "Bags",
    "subcategory": "",
    "price": 80,
    "sale": 48,
    "image": "assets/products/tao-tote-tropical-night.jpg",
    "desc": "The Tao tote after dark — deep tropical tones woven through a generous, shoulder-friendly silhouette.",
    "featured": false,
    "isNew": true,
    "image2": "assets/products/tao-tote-tropical-night-2.jpg"
  },
  {
    "id": "tao-tote",
    "name": "Tao tote",
    "category": "Bags",
    "subcategory": "",
    "price": 80,
    "sale": 48,
    "image": "assets/products/tao-tote.jpg",
    "desc": "A clean-lined everyday tote in our signature stitch. Carries the laptop, the lunch, the whole plan.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/tao-tote-2.jpg"
  },
  {
    "id": "kay-bucket-hat",
    "name": "Kay wavy bucket hat",
    "category": "Accessories",
    "subcategory": "Hats",
    "price": 45,
    "sale": 31.5,
    "image": "assets/products/kay-bucket-hat.jpg",
    "desc": "The Kay bucket hat with a wavy, hand-shaped brim. Sun cover with personality.",
    "featured": true,
    "isNew": false,
    "image2": "assets/products/kay-bucket-hat-2.jpg"
  },
  {
    "id": "bandana-sunset",
    "name": "Picot Bandana (sunset)",
    "category": "Accessories",
    "subcategory": "Bandanas",
    "price": 35,
    "sale": 24.5,
    "image": "assets/products/bandana-sunset.jpg",
    "desc": "Sunset-striped picot bandana — warm ombré tones for golden hour, all day.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/bandana-sunset-2.jpg"
  },
  {
    "id": "nae-bag-peach",
    "name": "Nae bag (peach)",
    "category": "Bags",
    "subcategory": "",
    "price": 90,
    "sale": 54,
    "image": "assets/products/nae-bag-peach.jpg",
    "desc": "A little peach crescent bag with a hand-stitched grip. The small bag that finishes everything.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/nae-bag-peach-2.jpg"
  },
  {
    "id": "bandana-buttercream",
    "name": "Picot Bandana (buttercream)",
    "category": "Accessories",
    "subcategory": "Bandanas",
    "price": 35,
    "sale": 24.5,
    "image": "assets/products/bandana-buttercream.jpg",
    "desc": "A soft buttercream bandana with a delicate picot trim.",
    "featured": false,
    "isNew": false,
    "image2": null
  },
  {
    "id": "purple-haze-mesh-small",
    "name": "Ivy Purple haze mesh (small)",
    "category": "Bags",
    "subcategory": "",
    "price": 100,
    "sale": 60,
    "image": "assets/products/purple-haze-mesh-small.jpg",
    "desc": "Purple-haze mesh in the small size — see-through, summer-bright and endlessly packable.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/purple-haze-mesh-small-2.jpg"
  },
  {
    "id": "ahoy-mesh-small",
    "name": "Ivy Ahoy mesh (small)",
    "category": "Bags",
    "subcategory": "",
    "price": 85,
    "sale": 51,
    "image": "assets/products/ahoy-mesh-small.jpg",
    "desc": "An airy open-weave mesh bag — beach-ready, market-ready, throw-everything-in ready.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/ahoy-mesh-small-2.jpg"
  },
  {
    "id": "blossom-loaf-cat",
    "name": "Blossom loaf cat",
    "category": "Plushies",
    "subcategory": "Loaf Cats",
    "price": 70,
    "sale": 42,
    "image": "assets/products/blossom-loaf-cat.jpg",
    "desc": "A loaf-shaped cat whose only job is to sit and be adored. Crocheted in soft velvet yarn for your shelf.",
    "featured": true,
    "isNew": false,
    "image2": null
  },
  {
    "id": "bloom-loaf-cat",
    "name": "Bloom loaf cat",
    "category": "Plushies",
    "subcategory": "Loaf Cats",
    "price": 70,
    "sale": 42,
    "image": "assets/products/bloom-loaf-cat.jpg",
    "desc": "The Bloom colourway of our cult loaf cat — a plump, palm-sized companion stitched to slouch like the real thing.",
    "featured": false,
    "isNew": false,
    "image2": null
  },
  {
    "id": "dana-tote-mustard",
    "name": "Dana tote (mustard)",
    "category": "Bags",
    "subcategory": "",
    "price": 80,
    "sale": 48,
    "image": "assets/products/dana-tote-mustard.jpg",
    "desc": "The Dana in warm mustard — a single-tone take on our roomiest carry.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/dana-tote-mustard-2.jpg"
  },
  {
    "id": "dana-tote-brown",
    "name": "Dana tote (brown)",
    "category": "Bags",
    "subcategory": "",
    "price": 80,
    "sale": 48,
    "image": "assets/products/dana-tote-brown.jpg",
    "desc": "The Dana in toasted brown. Neutral, hardwearing, quietly perfect.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/dana-tote-brown-2.jpg"
  },
  {
    "id": "dana-tote-bag-black",
    "name": "Dana tote (black)",
    "category": "Bags",
    "subcategory": "",
    "price": 80,
    "sale": 48,
    "image": "assets/products/dana-tote-bag-black.jpg",
    "desc": "The Dana in true black — the handmade tote that goes with everything you own.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/dana-tote-bag-black-2.jpg"
  },
  {
    "id": "burgundy-velvet",
    "name": "Burgundy velvet",
    "category": "Accessories",
    "subcategory": "Scrunchies",
    "price": 20,
    "sale": 14,
    "image": "assets/products/burgundy-velvet.jpg",
    "desc": "Velvet-yarn scrunchie in rich burgundy.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/burgundy-velvet-2.jpg"
  },
  {
    "id": "navy-velvet",
    "name": "Navy velvet",
    "category": "Accessories",
    "subcategory": "Scrunchies",
    "price": 20,
    "sale": 14,
    "image": "assets/products/navy-velvet.jpg",
    "desc": "Velvet-yarn scrunchie in navy — the everyday neutral.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/navy-velvet-2.jpg"
  },
  {
    "id": "white-velvet",
    "name": "White velvet",
    "category": "Accessories",
    "subcategory": "Scrunchies",
    "price": 20,
    "sale": 14,
    "image": "assets/products/white-velvet.jpg",
    "desc": "Velvet-yarn scrunchie in soft white.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/white-velvet-2.jpg"
  },
  {
    "id": "brown-velvet",
    "name": "Brown velvet",
    "category": "Accessories",
    "subcategory": "Scrunchies",
    "price": 20,
    "sale": 14,
    "image": "assets/products/brown-velvet.jpg",
    "desc": "Velvet-yarn scrunchie in chocolate brown.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/brown-velvet-2.jpg"
  },
  {
    "id": "grey-mix-velvet",
    "name": "Grey mix velvet",
    "category": "Accessories",
    "subcategory": "Scrunchies",
    "price": 20,
    "sale": 14,
    "image": "assets/products/grey-mix-velvet.jpg",
    "desc": "Velvet-yarn scrunchie in a heathered grey mix.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/grey-mix-velvet-2.jpg"
  },
  {
    "id": "scallop-bandana",
    "name": "Scallop bandana (blue)",
    "category": "Accessories",
    "subcategory": "Bandanas",
    "price": 35,
    "sale": 24.5,
    "image": "assets/products/scallop-bandana.jpg",
    "desc": "A scalloped-edge bandana in cool blue — a little more drama at the hairline.",
    "featured": false,
    "isNew": true,
    "image2": null
  },
  {
    "id": "jumbo-loaf-cat",
    "name": "Mai loaf cat",
    "category": "Plushies",
    "subcategory": "Loaf Cats",
    "price": 65,
    "sale": 45.5,
    "image": "assets/products/jumbo-loaf-cat.jpg",
    "desc": "Mai is the jumbo of the loaf litter — extra squish, extra presence. A statement plushie for grown-up shelves.",
    "featured": false,
    "isNew": true,
    "image2": null
  },
  {
    "id": "brook-sun-hat",
    "name": "Brook sun hat",
    "category": "Accessories",
    "subcategory": "Hats",
    "price": 45,
    "sale": 31.5,
    "image": "assets/products/brook-sun-hat.jpg",
    "desc": "A wide-brim crochet sun hat for slow, bright days.",
    "featured": false,
    "isNew": false,
    "image2": "assets/products/brook-sun-hat-2.jpg"
  }
];
