/* Generates a single-file `_worker.js` (Cloudflare Pages Advanced mode) that
   the dashboard Direct Upload WILL run (a /functions folder is not compiled by
   drag-and-drop, but a root _worker.js is). Inlines the server-side price map
   and serves all static assets via env.ASSETS.

   Run:  node build-worker.js  (writes to the path given as arg, default ./_worker.js)
*/
const fs = require("fs");
globalThis.window = {};
require("./js/catalog.js");
const CATALOG = window.CATALOG;

const map = {};
for (const p of CATALOG) {
  const priceAed = p.sale != null ? p.sale : p.price;
  map[p.id] = { name: p.name, amount: Math.round(priceAed * 100), image: p.image };
}

const out = `// AUTO-GENERATED by build-worker.js — do not edit by hand.
// Cloudflare Pages Advanced-mode worker: serves static assets + POST /api/checkout.
const PRODUCTS = ${JSON.stringify(map)};

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/api/checkout") {
      if (request.method !== "POST") return new Response("Method not allowed", { status: 405 });
      return handleCheckout(request, env);
    }
    return env.ASSETS.fetch(request);
  },
};

async function handleCheckout(request, env) {
  const json = (data, status = 200) =>
    new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json" } });

  if (!env.STRIPE_SECRET_KEY) return json({ error: "Stripe is not configured yet (missing STRIPE_SECRET_KEY)." }, 500);

  let body;
  try { body = await request.json(); } catch { return json({ error: "Invalid request." }, 400); }
  const items = Array.isArray(body && body.items) ? body.items : [];
  if (!items.length) return json({ error: "Your basket is empty." }, 400);

  const origin = new URL(request.url).origin;
  const params = new URLSearchParams();
  params.set("mode", "payment");
  params.set("success_url", origin + "/success.html?paid=1&session_id={CHECKOUT_SESSION_ID}");
  params.set("cancel_url", origin + "/?checkout=cancelled");
  params.set("phone_number_collection[enabled]", "true");
  ["AE", "SA", "OM", "BH", "KW", "QA", "GB", "US"].forEach((c, i) =>
    params.set("shipping_address_collection[allowed_countries][" + i + "]", c));

  let line = 0;
  for (const it of items) {
    const p = PRODUCTS[it.id];
    if (!p) continue;
    const quantity = Math.max(1, Math.min(99, parseInt(it.qty, 10) || 1));
    params.set("line_items[" + line + "][quantity]", String(quantity));
    params.set("line_items[" + line + "][price_data][currency]", "aed");
    params.set("line_items[" + line + "][price_data][unit_amount]", String(p.amount));
    params.set("line_items[" + line + "][price_data][product_data][name]", p.name);
    if (p.image) params.set("line_items[" + line + "][price_data][product_data][images][0]", new URL(p.image, origin).href);
    line++;
  }
  if (line === 0) return json({ error: "No valid items in basket." }, 400);

  const res = await fetch("https://api.stripe.com/v1/checkout/sessions", {
    method: "POST",
    headers: { Authorization: "Bearer " + env.STRIPE_SECRET_KEY, "Content-Type": "application/x-www-form-urlencoded" },
    body: params,
  });
  const session = await res.json();
  if (!res.ok) return json({ error: (session.error && session.error.message) || "Could not start checkout." }, 502);
  return json({ url: session.url });
}
`;

const dest = process.argv[2] || "./_worker.js";
fs.writeFileSync(dest, out);
console.log("wrote " + dest + " (" + Object.keys(map).length + " products inlined, " + out.length + " bytes)");
