/* Generates a single-file `_worker.js` (Cloudflare Pages Advanced mode).
   Inlines the server-side price + stock map and exposes:
     POST /api/checkout        — creates a Stripe Checkout session (guards stock)
     GET  /api/stock           — current sold counts (from D1), for the storefront
     POST /api/stripe-webhook  — decrements stock on paid orders (verified)

   Inventory model: each product's total `stock` is set in the CMS (blank = unlimited).
   D1 table `sales` counts how many have sold. Available = stock - sold.
   Everything degrades safely if env.DB / STRIPE_WEBHOOK_SECRET aren't set yet.

   Run:  node build-worker.js [destination]   (default ./_worker.js)
*/
const fs = require("fs");
globalThis.window = {};
require("./js/catalog.js");
const CATALOG = window.CATALOG;

const map = {};
for (const p of CATALOG) {
  const priceAed = p.sale != null ? p.sale : p.price;
  const stock = p.stock === undefined || p.stock === null || p.stock === "" ? null : Number(p.stock);
  map[p.id] = { name: p.name, amount: Math.round(priceAed * 100), image: p.image, stock: Number.isFinite(stock) ? stock : null };
}

const out = `// AUTO-GENERATED by build-worker.js — do not edit by hand.
const PRODUCTS = ${JSON.stringify(map)};

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === "/api/checkout")
      return request.method === "POST" ? handleCheckout(request, env) : new Response("Method not allowed", { status: 405 });
    if (url.pathname === "/api/stock")
      return handleStock(env);
    if (url.pathname === "/api/stripe-webhook")
      return request.method === "POST" ? handleWebhook(request, env) : new Response("Method not allowed", { status: 405 });
    return env.ASSETS.fetch(request);
  },
};

const J = (data, status = 200) =>
  new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json", "Cache-Control": "no-store" } });

// How many of each product have sold (from D1). Empty if the DB isn't bound yet.
async function soldMap(env) {
  if (!env.DB) return {};
  try {
    const { results } = await env.DB.prepare("SELECT product_id, sold FROM sales").all();
    const m = {};
    for (const r of results || []) m[r.product_id] = r.sold;
    return m;
  } catch { return {}; }
}

async function handleStock(env) {
  return J({ sold: await soldMap(env) });
}

async function handleCheckout(request, env) {
  if (!env.STRIPE_SECRET_KEY) return J({ error: "Stripe is not configured yet (missing STRIPE_SECRET_KEY)." }, 500);

  let body;
  try { body = await request.json(); } catch { return J({ error: "Invalid request." }, 400); }
  const items = Array.isArray(body && body.items) ? body.items : [];
  if (!items.length) return J({ error: "Your basket is empty." }, 400);

  // Inventory guard — block sold-out / over-quantity for tracked products.
  const sold = await soldMap(env);
  for (const it of items) {
    const p = PRODUCTS[it.id];
    if (!p || p.stock == null) continue;
    const want = Math.max(1, parseInt(it.qty, 10) || 1);
    const avail = p.stock - (sold[it.id] || 0);
    if (avail <= 0) return J({ error: '"' + p.name + '" just sold out.', soldOut: it.id }, 409);
    if (want > avail) return J({ error: "Only " + avail + ' of "' + p.name + '" left.', max: avail, id: it.id }, 409);
  }

  const origin = new URL(request.url).origin;
  const params = new URLSearchParams();
  params.set("mode", "payment");
  params.set("success_url", origin + "/success.html?paid=1&session_id={CHECKOUT_SESSION_ID}");
  params.set("cancel_url", origin + "/?checkout=cancelled");
  params.set("phone_number_collection[enabled]", "true");
  // UAE-only online checkout (international orders are arranged by DM, per the shipping page).
  params.set("shipping_address_collection[allowed_countries][0]", "AE");

  const meta = [];
  let line = 0, subtotal = 0;
  for (const it of items) {
    const p = PRODUCTS[it.id];
    if (!p) continue;
    const quantity = Math.max(1, Math.min(99, parseInt(it.qty, 10) || 1));
    subtotal += p.amount * quantity;
    params.set("line_items[" + line + "][quantity]", String(quantity));
    params.set("line_items[" + line + "][price_data][currency]", "aed");
    params.set("line_items[" + line + "][price_data][unit_amount]", String(p.amount));
    params.set("line_items[" + line + "][price_data][product_data][name]", p.name);
    if (p.image) params.set("line_items[" + line + "][price_data][product_data][images][0]", new URL(p.image, origin).href);
    meta.push(it.id + ":" + quantity);
    line++;
  }
  if (line === 0) return J({ error: "No valid items in basket." }, 400);
  params.set("metadata[items]", meta.join(",").slice(0, 480));

  // Delivery: flat AED 20 under AED 250, free at/above AED 250.
  const freeShip = subtotal >= 25000;
  params.set("shipping_options[0][shipping_rate_data][type]", "fixed_amount");
  params.set("shipping_options[0][shipping_rate_data][fixed_amount][amount]", freeShip ? "0" : "2000");
  params.set("shipping_options[0][shipping_rate_data][fixed_amount][currency]", "aed");
  params.set("shipping_options[0][shipping_rate_data][display_name]", freeShip ? "Free UAE delivery" : "UAE delivery");

  const res = await fetch("https://api.stripe.com/v1/checkout/sessions", {
    method: "POST",
    headers: { Authorization: "Bearer " + env.STRIPE_SECRET_KEY, "Content-Type": "application/x-www-form-urlencoded" },
    body: params,
  });
  const session = await res.json();
  if (!res.ok) return J({ error: (session.error && session.error.message) || "Could not start checkout." }, 502);
  return J({ url: session.url });
}

async function handleWebhook(request, env) {
  const body = await request.text();
  if (!env.STRIPE_WEBHOOK_SECRET) return new Response("ok", { status: 200 });
  if (!(await verifySig(body, request.headers.get("Stripe-Signature") || "", env.STRIPE_WEBHOOK_SECRET)))
    return new Response("bad signature", { status: 400 });

  let event;
  try { event = JSON.parse(body); } catch { return new Response("bad json", { status: 400 }); }

  if (event.type === "checkout.session.completed" && env.DB) {
    const meta = (((event.data || {}).object || {}).metadata || {}).items || "";
    for (const part of meta.split(",")) {
      const [id, q] = part.split(":");
      const qty = Math.max(1, parseInt(q, 10) || 0);
      if (!id || !qty) continue;
      try {
        await env.DB.prepare(
          "INSERT INTO sales (product_id, sold) VALUES (?1, ?2) ON CONFLICT(product_id) DO UPDATE SET sold = sold + ?2"
        ).bind(id, qty).run();
      } catch {}
    }
  }
  return new Response("ok", { status: 200 });
}

// Verify Stripe's webhook signature (t=…,v1=… header) with Web Crypto HMAC-SHA256.
async function verifySig(payload, header, secret) {
  const parts = {};
  header.split(",").forEach((kv) => { const i = kv.indexOf("="); if (i > 0) parts[kv.slice(0, i)] = kv.slice(i + 1); });
  const t = parts.t, v1 = parts.v1;
  if (!t || !v1) return false;
  if (Math.abs(Date.now() / 1000 - Number(t)) > 300) return false;
  const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const buf = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(t + "." + payload));
  const expected = [...new Uint8Array(buf)].map((b) => b.toString(16).padStart(2, "0")).join("");
  if (expected.length !== v1.length) return false;
  let diff = 0;
  for (let i = 0; i < expected.length; i++) diff |= expected.charCodeAt(i) ^ v1.charCodeAt(i);
  return diff === 0;
}
`;

const dest = process.argv[2] || "./_worker.js";
fs.writeFileSync(dest, out);
const tracked = Object.values(map).filter((p) => p.stock != null).length;
console.log("wrote " + dest + " (" + Object.keys(map).length + " products, " + tracked + " with stock limits, " + out.length + " bytes)");
